### PR TITLE
Sort games and use existing Steam instance

### PR DESCRIPTION
**Pull request by bemug**

### CODE REVIEW

**Comment by SFort** [comment]
oh wow i didn't even see this, ty github.
tells me there's a branch been made _twice_, but dosn't notify about a PR.
(refrance to conversation prior to me realizing there's a pr [98ab552](https://github.com/bemug/steam-dmenu/commit/98ab552e9ab75d7c4435f642b8f2e97a8853db38))

i intend to keep xdg-open as it allows easy redirection of the `steam://` uri and it doesn't make duplicate instances as long as it's pointed to the same executable. (also pretty sure it's what all browsers use and by proxy so does the steam website)

what this does make me realize is that `steam_dmenu -o | sort | steam_dmenu` doesn't work while it really should, feel free to pr that if not i'll get around to it soon-ish

**Comment by bemug** [comment]
> i intend to keep xdg-open as it allows easy redirection of the `steam://` uri and it doesn't make duplicate instances as long as it's pointed to the same executable. (also pretty sure it's what all browsers use and by proxy so does the steam website)

Sure, as said it's a problem on my side, please disregard this.

> what this does make me realize is that `steam_dmenu -o | sort | steam_dmenu` doesn't work while it really should, feel free to pr that if not i'll get around to it soon-ish

Isn't it because it sorts game ids and game names at the same time? The sort on this PR is after the game id and game association done by your printf ;)

**Comment by SFort** [comment]
tested the sorting using `./steam_dmenu.sh -o | sort | grep -v 'Proton\|Runtime\|SDK\|SteamVR\|Steamworks' | ./steam_dmenu.sh -d 'bemenu -i'` and seames to be working now

**Comment by bemug** [comment]
Any reason for not adding the sort directly in the `steam_dmenu.sh` instead of using the `-o`? This will preserve the behavior from the original `steam_dmenu.py`

**Comment by SFort** [comment]
if someone wanted a diffrent sort (or filter before a sort) it just seames silly to sort it and then have it sorted again
(no clue if it would actually matter when having lot's of games installed)
but ye i don't __really__ have a good reason, just being pedantic

**Pull request closed without merging**
